module.exports = {
  ms_version: "v1",
  microservices: {
    ACCOUNTS: "/accounts",
    ACTIVITY: "/activity",
    AUTH: "/auth",
    CAMPAIGNS: "/sms",
    CHAT: "/chat",
    CONTACTS: "/contacts",
    DBSIP: "/dbsip",
    EMAIL: "/email",
    ENTITLEMENTS: "/entitlements",
    FORMS: "/forms",
    GROUPS: "/groups",
    IDENTITY: "/identity",
    LAMBDA: "/lambda",
    MEDIA: "/media",
    MESSAGING: "/messaging",
    METADATA: "/metadata",
    MOBILE: "/mobilenotification",
    NUMBERS: "/sms",
    OAUTH: "/oauth",
    OBJECTS: "/objects",
    PROFILES: "/profiles",
    PROVIDERS: "/providers",
    PUBSUB: "/pubsub",
    RESOURCES: "/resourcecms",
    SCHEDULER: "/scheduler",
    SHORTURLS: "/shorturl",
    SMS: "/sms",
    USAGE: "/usage",
    VOICE: "/voice",
    WORKFLOW: "/workflow",
  },
  msDelay: 1000,
  pollInterval: 1000,
  pollTimeout: 9000,
  resourceRoleDescriptions: {
    objects: "system role - 01e77463-bf4e-453d-8a89-c145f83d3f54",
  },
};
